title: CommonTK Wiki Archive
description: Archived documentation from the CommonTK project
markdown: kramdown
theme: jekyll-theme-cayman
repository: sjh26/ctk-wiki-archive

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
